server:
  port: 7090
  servlet:
    context-path: /auth

jwt:
  converter:
    resource-id: authenticationClientId

keycloak:
  realm: bisky-music
  domain: localhost:9081
  adminClientId: admin-cli
  adminClientSecret: TEtZtd6d22kaWEV7tFcxxAf3WHoYe85x
  client: authenticationClientId
  urls:
    auth: http://${keycloak.domain}

spring:
  profile:
    active: production

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9081/realms/${keycloak.realm}
