server:
  port: 7090
  servlet:
    context-path: /auth

jwt:
  converter:
    resource-id: authenticationClientId

keycloak:
  realm: bisky-music
  domain: keycloak.codewithbisky.com
  adminClientId: admin-cli
  adminClientSecret: Sr2cyqeesLrSN0AvbRfgjwU8N9Skx
  client: authenticationClientId
  urls:
    auth: https://${keycloak.domain}

spring:
  profile:
    active: production

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9081/realms/${keycloak.realm}
